# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["hi+fastly@mxdvl.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript"
description = "Playground for experimenting with Compute@edge"
language = "javascript"
manifest_version = 3
name = "fastly-compute-edge"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"
